version: '2'

services:
    web:
        build: ./docker
        container_name: www_docker_php
        ports:
            - "8099:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./code/:/var/www/html/
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./code:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
